### ISSUE TITLE
ERROR: Incorrectly formatted sample file at line1

### ISSUE THREAD

**Issue by yingxi-kaylee** [rgcgithub/regenie#57]
Dear REGENIE team,

I specify the sample file corresponding to my input BGEN file using '--sample' option but got the following error:

 ERROR: Incorrectly formatted sample file at line1.

My sample file has the following format:

ID_1 ID_2
0 0
5801985 5801985
5577286 5577286
1992118 1992118
2955524 2955524

I'm using REGENIE v1.0.6.6. Any thoughts about why this error? Much appreciated!

**Comment by joellembatchou** [comment]
Hi,

This has been fixed in commit c5661751e258d6a596fc8f6ed395ca4ff4b5f23a.

Cheers,
Joelle

**Comment by sariya** [comment]
@joellembatchou: Sorry to revive this old issue.
I still get this error. ` REGENIE v1.0.6.7.gz` 

Below is the code for step 1 and step2 and other steps performed to create .bgen file and its index:

```
regenie --step 1 \
  --bed updatedids_removedSNPs_hg38_notfoundTOPMED_alleles  \
  --covarFile regenie_phenotype.txt --covarColList AGE,SEX,PC1,PC2,PC3 \
 --remove  remove_individuals.txt \
  --phenoFile regenie_phenotype.txt --phenoCol AD --phenoColList AD \
  --bsize 100 --bt --lowmem --out step1_reg

--
regenie   --step 2 \
--bgen CHR22_rsq40.bgen \
--covarFile regenie_phenotype.txt --covarColList AGE,SEX,PC1,PC2,PC3  \
--phenoFile regenie_phenotype.txt \
--phenoCol AD--phenoColList AD \
--remove  remove_individuals.txt  --bsize 200 --sample samples.txt \
--bt --firth --approx --pThresh 0.99 --pred step1_reg_pred.list --out CHR22_bin_out_firth

```

Get samples using qctools from .bgen file

```
qctool -g CHR22_rsq40.bgen   -os samples.txt
 ```

I converted topmed imputed files to bgen using plink. I think plink doesn't add FID/IIDs in the .bgen files.  https://github.com/rgcgithub/regenie/issues/10#issuecomment-655874495 

```
plink2 \
--vcf chr"$chr".dose.vcf.gz 'dosage=DS' \
--export bgen-1.2 'bits=8' --extract CHR"$chr"_rsq40_snps.txt --out CHR"$chr"_rsq40
```

Index was created as: 

```
bgenix -clobber -g ./CHR"$chr"_rsq40.bgen -index
```

I have tried removing `ID_1    ID_2` followed by `0 0` in second row. I have tried with just `ID_1    ID_2` and not second row as `0 0`.

How do I resolve this? 

Thank you.

**Comment by joellembatchou** [comment]
Hi,

Could you try with the more recent Regenie version 2.0.2?

**Comment by sariya** [comment]
Thank you. yes, no more error with 2.0.2 regenie

**Comment by lilipeng** [comment]
Hi all, I just ran regenie v. step 2 with a variant annotation input file. I get the error: " * annotations      : [/home/lpeng1/gaba-ar/annotation_domain2.txt] 
ERROR: incorrectly formatted file at line 1"

Here is the file: 
5:161854169:C:A        GENE1   missense
5:161854169:C:G        GENE1   missense
5:161854169:C:T        GENE1   missense
5:161294271:C:G        GENE2   missense
5:161294271:C:T        GENE2   missense
5:162103900:C:T        GENE3   missense

What is the problem with the format? I"m using Regenie/3.1.3.

**Comment by joellembatchou** [comment]
Can you check if there are any special characters persent? (ie `cat -A ~/home/lp/annotation_domain2.txt`)
