### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by GHawkes93** [rgcgithub/regenie#58]
Hi,
Thank you for making this software available!

When running REGENIE I am encountering the following error at the end of step 1:

**terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc**

The  end of the output file is as so

**Level 1 ridge...
   -on phenotype 1 (regenie_test)...done (441055ms) 

Output
------
phenotype 1 (regenie_test) :**

I have checked that my memory is sufficient, and that the input files are being read in correctly. I have also tried running the analyses in low memory mode, but this doesn't seem to overcome the problem. Do you have any suggestions as to what is causing this?

Thanks for your help and time,
Gareth

**Comment by joellembatchou** [comment]
Hi Gareth,

Which operating system are you using? I have pushed an edit in this commit (commit 247483cd5617f048682062553265837c2b95d6ee) to address this error.

Cheers,
Joelle

**Comment by GHawkes93** [comment]
Hi Joelle,

Thank you - I will recompile now and see if it fixes the error (I should be able to let you know in about 24 hours!).

I'm running REGENIE on a remote Linux-based server.

Cheers,
Gareth

**Comment by GHawkes93** [comment]
Hi Joelle,

Unfortunately that doesn't seem to have done the trick - still getting the error at the exact same point.

Cheers,
Gareth

**Comment by joellembatchou** [comment]
Hi Gareth,

Can you try running the test commands:
```
./test/test_bash.sh --path .
```
and check whether it runs successfully?

**Comment by GHawkes93** [comment]
Hi Joelle,

Ah, you might've found the problem there. I get the following output:

Running step 1 of REGENIE
==================================
./regenie: /lib64/libgomp.so.1: version `GOMP_4.5' not found (required by ./regenie)
./regenie: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./regenie)
./regenie: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./regenie)
./regenie: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./regenie)
Step 1 of REGENIE did not finish successfully. Update to most recent REGENIE version (using 'git pull') and re-compile the software (using 'make clean && make').

I had been assuming that if it compiled and loaded in the input files correctly then it was fine!
This is from a git clone on Friday morning, so not sure why its gone wrong!

Cheers,
Gareth

**Comment by GHawkes93** [comment]
Ah, hang on sorry I forgot to load in GCC before running it.

Here's the actual output:

Running step 1 of REGENIE
==================================
Start time: Mon Nov 23 15:30:40 2020

              |==============================|
              |        REGENIE v1.0.6.7      |
              |==============================|

Copyright (c) 2020 Joelle Mbatchou and Jonathan Marchini.
Distributed under the MIT License.

Log of output saved in file : test/fit_bin_out.log

Options in effect:
  --step 1 \
  --bed example/example \
  --exclude example/snplist_rm.txt \
  --covarFile example/covariates.txt \
  --phenoFile example/phenotype_bin.txt \
  --remove example/fid_iid_to_remove.txt \
  --bsize 100 \
  --bt \
  --lowmem \
  --lowmem-prefix tmp_rg \
  --out test/fit_bin_out

Fitting null model
 * bim              : [example/example.bim] n_snps = 1000
   -removing variants specified in [example/snplist_rm.txt]
     +number of variants remaining in the analysis = 994
 * fam              : [example/example.fam] n_samples = 500
   -removing individuals specified in [example/fid_iid_to_remove.txt]
     +number of genotyped individuals to exclude from the analysis = 6
 * bed              : [example/example.bed]
 * phenotypes       : [example/phenotype_bin.txt] n_pheno = 2
   -number of phenotyped individuals = 494
 * covariates       : [example/covariates.txt] n_cov = 3
   -number of individuals with covariate data = 494
 * number of individuals used in analysis = 494
   -fitting null logistic regression on binary phenotypes...done (1ms)
   -residualizing and scaling phenotypes...done (0ms)
   -WARNING: Sample size is less than 5,000 so using LOOCV instead of 5-fold CV.
 * # threads        : [16]
 * block size       : [100]
 * # blocks         : [10]
 * # CV folds       : [494]
 * ridge data_l0    : [5 : 0.01 0.25 0.5 0.75 0.99 ]
 * ridge data_l1    : [5 : 0.01 0.25 0.5 0.75 0.99 ]
 * approximate memory usage : 955MB
 * writing level 0 predictions to disk
   -temporary files will have prefix [tmp_rg_l0_Y]
   -approximate disk space needed : 1MB
 * setting memory...done

Chromosome 1
 block [1] : 100 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (56ms)
   -calc level 0 ridge...done (11ms)
 block [2] : 100 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (5ms)
   -calc level 0 ridge...done (7ms)
 block [3] : 100 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (51ms)
   -calc level 0 ridge...done (2ms)
 block [4] : 100 snps  (1ms)
   -residualizing and scaling genotypes...done (1ms)
   -calc working matrices...done (46ms)
   -calc level 0 ridge...done (12ms)
 block [5] : 100 snps  (1ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (38ms)
   -calc level 0 ridge...done (13ms)
 block [6] : 100 snps  (0ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (50ms)
   -calc level 0 ridge...done (11ms)
 block [7] : 100 snps  (0ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (59ms)
   -calc level 0 ridge...done (15ms)
 block [8] : 100 snps  (0ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (3ms)
   -calc level 0 ridge...done (1ms)
 block [9] : 100 snps  (0ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (22ms)
   -calc level 0 ridge...done (14ms)
 block [10] : 94 snps  (0ms)
   -residualizing and scaling genotypes...done (0ms)
   -calc working matrices...done (51ms)
   -calc level 0 ridge...done (9ms)

 Level 1 ridge with logistic regression...
   -on phenotype 1 (Y1)...done (26ms)
   -on phenotype 2 (Y2)...done (8ms)

Output
------
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
phenotype 1 (Y1) : ./test/test_bash.sh: line 63: 27435 Aborted                 ./$regenie_bin $rgcmd
Step 1 of REGENIE did not finish successfully. Update to most recent REGENIE version (using 'git pull') and re-compile the software (using 'make clean && make').

**Comment by joellembatchou** [comment]
Which Linux OS are you using to run this?

**Comment by GHawkes93** [comment]
Here's the details of the server:

Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-327.22.2.el7.x86_64
Architecture: x86-64

**Comment by matuskosut** [comment]
Hi @GHawkes93,

would it make sense to try conda installation? https://github.com/rgcgithub/regenie/issues/51
To me it seems like some inconsistency of dependencies installed in your system that doesn't get catched in compilation. I have met this same error when creating conda package, but unfortunatelly don't remember what was the issue with compilers. I would also point out that kernel 3.10.0-372 is around 5 years old. 

Finding out the problem might be quite difficult, but if you are eager for that option, maybe you will want to try compiling regenie in debug and using `valgrind` for analysis of memory allocations problems in runtime.

**Comment by GHawkes93** [comment]
Hi @matuskosut,

I would prefer to do things with the raw executable, if possible, due to the sheer size of the input files I'm dropping in (I admittedly don't know how well conda can cope with this).

If the raw executable becomes impossible to solve, I'll take a deeper look.

Cheers,
Gareth

**Comment by matuskosut** [comment]
@GHawkes93 sorry, I think we misunderstood, maybe I should have given more info. Firstly, Conda is just a package manager, that helps to install packages which contain libraries and executables, think of similar ones like: dnf, apt, or pip (python). 

So good info is that there is no dropping files onto conda or bioconda. Regenie package is installable from bioconda, which is an initiative to give researchers easy way to get their executables on their computer (or server) and assure these packages will work on their platform because it will include necessary dependencies. All that by running: `conda install -c bioconda regenie`, even though yes you will need conda to run this command.

**Comment by joellembatchou** [comment]
Hi Gareth,

I am not sure if you were able to resolve the issue. There is a[ Centos 7 pre-compiled binary](https://github.com/rgcgithub/regenie/releases/tag/v1.0.6.7) available for Regenie v1.0.6.7, could you try running the test command with this binary?

**Comment by GHawkes93** [comment]
Hi Joelle,

I've tried running the test run, and its gone through both steps sucessfully! 

I'm running a real phenotype now - will let you know the results.

Cheers,
Gareth

**Comment by GHawkes93** [comment]
Hi Joelle,

All seems to be working now - thanks for all of your help!

Are there any plans to add a maf filter into step 1 to avoid the variance issue? 

Cheers,
Gareth

**Comment by joellembatchou** [comment]
Hi Gareth,

Because of how Regenie reads in the genotype file in step 1 (in blocks of variants), it is not possible to know in advance which variants are problematic (i.e. variance=0) unless going through the whole file. Hence, it is recommended to do the adequate QC prior to the Regenie call so as to exclude these.

Cheers,
Joelle

**Comment by GHawkes93** [comment]
Hi Joelle,

Ah, okay that makes sense. The problem we were hitting is that the problematic SNPs are dependent upon the phenotype (e.g. a full coverage continuous versus a limited binary), so we didn't want to have to keep generating bed files etc. But I suppose the easiest way is just to use a bed file which works for everything!

Thanks again,
Gareth

**Comment by joellembatchou** [comment]
Hi Gareth, 

Regenie can take a list of SNPs to use for step 1 (option `--extract`) so you can bypass having to generate a new file by just passing that list of SNPs along with the full genotype file (for example in PLINK2, you'd use option `--write-snplist` when applying the QC filters).

Cheers,
Joelle
